services:
  web:
    container_name: web_app
    build: .
    command: >
      bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/test
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test

volumes:
  postgres_data: